### ISSUE TITLE
程序无法获取Spotify播放状态

### ISSUE THREAD

**Issue by Afterthou9hts** [Mai-icy/Spotify-lyrics-window#24]
只能通过按下刷新按钮这一种方法主动获取歌词。
看起来程序似乎无法获取Spotify的播放状态，Spotify开始播放时无法同步搜寻歌词，歌词不会随播放器暂停而停止，快进也无法跟随。
在windowsPC已尝试通过Webplayer与Spotify app播放，均无法与播放同步。
同样，无法通过按钮操控Spotify播放。
刷新同步后自然播放结束时可以正常更新到下一首曲目的歌词。

log如下：

v1.8 on 23h2
Log:
ERROR - Unknown Error
Traceback (most recent call last):
  File "view\lyric_window\lyric_window.py", line 40, in __call__
  File "view\lyric_window\lyric_window.py", line 249, in pause_resume_button_event
  File "common\win_utils\media_session.py", line 201, in play_pause_media
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 612, in run_until_complete
  File "common\win_utils\media_session.py", line 99, in _media_async_operate
  File "common\win_utils\media_session.py", line 95, in _get_media_session
common.win_utils.media_session.NoSpotifyRunning

**Comment by Mai-icy** [comment]
程序没有连接到本地的spotify app，但貌似错误认为自己连接到了
某些本地的spotify app会因为其自身原因抓取不到app对应的程序id
如果在连接不到的情况下，正常会使用spotify官方提供的api接口

**Comment by Mai-icy** [comment]
官方提供的api貌似也有变化，太久没有维护项目，马上会做出更新

**Comment by Mai-icy** [comment]
已修复打包

**Comment by Mai-icy** [comment]
这个bug是打包没测的锅，requests这个异常使用可能有点bug，之后改了就好了（不打包还不会出这个问题）
0.5s个例都是spotify API的锅，仅会出现在spotify自动下一首歌的时候。
找不到spotify.exe是指在MediaSession中的名字，有的时候是乱七八糟的。

**Comment by Mai-icy** [comment]
扩大了MediaSession的获取范围，这次有可能可以连接到app了，并且修复了上面的问题

**Comment by Mai-icy** [comment]
可以连接桌面端spotify吗，如果成功连接上桌面端可以实时绑定
api延迟是正常的，api模式下悬浮窗不会主动更新状态

**Comment by Mai-icy** [comment]
如果连接成功，在调整桌面端歌曲进度的时候会自动对齐歌词位置

**Comment by SugarB1ade** [comment]
我也遇到類似問題 不過我是在播放途中自動切下一首歌的時候會出現這個
![image](https://github.com/user-attachments/assets/f5b738ad-6526-4893-9a77-62865cbf18dd)
有時候過一會又會恢復正常
2024-09-24 21:15:11,552 - ERROR - Unknown Error
Traceback (most recent call last):
  File "view\lyric_window\lyric_window.py", line 40, in __call__
  File "view\lyric_window\lyric_window.py", line 389, in _download_lyric
  File "common\lyric\lyric_download.py", line 27, in download_lrc
  File "common\api\

**Comment by Mai-icy** [comment]
log貌似不全？

**Comment by SugarB1ade** [comment]
![image](https://github.com/user-attachments/assets/3bbb83eb-3abd-4b67-9ca3-f247f9d2089d)
也有不少這樣的情況

**Comment by SugarB1ade** [comment]
> log貌似不全？

什麼意思?

**Comment by Mai-icy** [comment]
错误日志后面好像少了一截，是不是复制少了

**Comment by Mai-icy** [comment]
> 我也遇到類似問題 不過我是在播放途中自動切下一首歌的時候會出現這個 ![image](https://private-user-images.githubusercontent.com/129523527/370299666-f5b738ad-6526-4893-9a77-62865cbf18dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMzAzNTUsIm5iZiI6MTcyNzIzMDA1NSwicGF0aCI6Ii8xMjk1MjM1MjcvMzcwMjk5NjY2LWY1YjczOGFkLTY1MjYtNDg5My05YTc3LTYyODY1Y2JmMThkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwMjA3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDA0ZjBiN2VmODYyNmJhM2RjZjIyZGQxM2IyNTQyYzA1OTFkNjRkOTllMjMwMGZiZDA0M2ZmOWRlMGJmNTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZgOCdtBA9tagglPoINIPK8DUzLxA4F75xPAaEkOKWlE) 有時候過一會又會恢復正常 2024-09-24 21:15:11,552 - ERROR - Unknown Error Traceback (most recent call last): File "view\lyric_window\lyric_window.py", line 40, in **call** File "view\lyric_window\lyric_window.py", line 389, in _download_lyric File "common\lyric\lyric_download.py", line 27, in download_lrc File "common\api\

指的是这个，common\api\后面应该还有内容
